### ISSUE TITLE
Nota informativa 

### ISSUE THREAD

**Issue by Dasus2332** [SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-y#3]
[Nota informativa(2).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-y/files/9955884/Nota.informativa.2.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Bien hecho compañero 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
